# Generated by Django 2.2.1 on 2019-06-19 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0008_auto_20190616_1949'),
        ('RentACarService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vehiclereservation',
            name='flight_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FlightService.FlightReservation'),
        ),
        migrations.AddField(
            model_name='vehiclereservation',
            name='quick',
            field=models.BooleanField(default=False),
        ),
    ]
