# Generated by Django 2.2.1 on 2019-06-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RentACarService', '0002_auto_20190619_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclereservation',
            name='reserved_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='vehiclereservation',
            name='reserved_to',
            field=models.DateField(),
        ),
    ]
