# Generated by Django 2.2.1 on 2019-06-20 15:07

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('RentACarService', '0004_vehicle_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
