# Generated by Django 2.1.7 on 2019-04-13 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20190412_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friends',
            options={'verbose_name_plural': 'Friends'},
        ),
        migrations.AlterField(
            model_name='friends',
            name='current_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
