# Generated by Django 2.2.1 on 2019-05-14 19:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0008_auto_20190514_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HotelService', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_from', models.DateField()),
                ('reserved_to', models.DateField()),
                ('flight_reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FlightService.FlightReservation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HotelService.Room')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
