# Generated by Django 2.2.1 on 2019-06-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelService', '0002_roomrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
