# Generated by Django 2.2.1 on 2019-05-14 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HotelService', '0002_hotelreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelreservation',
            name='flight_reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FlightService.FlightReservation'),
        ),
    ]
