# Generated by Django 2.2.1 on 2019-06-19 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelService', '0003_auto_20190619_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
