# Generated by Django 2.1.7 on 2019-04-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='col',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flight',
            name='row',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
