# Generated by Django 2.2 on 2019-04-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='col',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='row',
        ),
        migrations.AddField(
            model_name='flight',
            name='cols_business',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='cols_economy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='cols_first',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='rows_business',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='rows_economy',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flight',
            name='rows_first',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
