# Generated by Django 2.2.1 on 2019-05-25 21:01

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='location',
            field=location_field.models.plain.PlainLocationField(max_length=63, null=True),
        ),
    ]
