# Generated by Django 2.2.1 on 2019-05-07 20:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0002_flightrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrating',
            name='rate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
