# Generated by Django 2.2.1 on 2019-05-25 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0002_destination_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='destination',
            name='lon',
        ),
    ]
