# Generated by Django 2.2 on 2019-04-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0002_auto_20190423_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='type',
            field=models.CharField(default='', max_length=10),
        ),
    ]
