# Generated by Django 2.2.1 on 2019-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0003_auto_20190525_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
