# Generated by Django 2.2 on 2019-04-21 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0003_flightreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightreservation',
            name='flight',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='FlightService.Flight'),
        ),
    ]
