# Generated by Django 2.2.1 on 2019-05-07 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0003_auto_20190507_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrating',
            name='rate',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
