# Generated by Django 2.2 on 2019-04-21 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0004_flightreservation_flight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightreservation',
            name='flight',
        ),
    ]
