# Generated by Django 2.2.1 on 2019-06-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0005_auto_20190614_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='connections',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
