# Generated by Django 2.2.1 on 2019-05-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0005_flightreservation_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightreservation',
            name='passport',
            field=models.CharField(default='', max_length=20),
        ),
    ]
