# Generated by Django 2.2.1 on 2019-06-16 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0006_flight_connections'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightreservation',
            name='date_created',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
