# Generated by Django 2.2.1 on 2019-06-16 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FlightService', '0007_flightreservation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightreservation',
            name='date_created',
            field=models.DateField(null=True),
        ),
    ]
